replicaCount: 1

image:
  repository: anhhao2004/nextjs-app
  tag: latest  # sẽ được Jenkins cập nhật sau mỗi build

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: nguyenanhhao.site
