replicaCount: 1

image:
  repository: anhhao2004/nextjs-app
  tag: latest  # sẽ được Jenkins cập nhật sau mỗi build

service:
  type: NodePort
  port: 3000
  nodePort: 30080

ingress:
  enabled: true
  host: nguyenanhhao.site
